### ISSUE TITLE
Error: Attempt to de-reference a null object

### ISSUE THREAD

**Issue by AshwinPandole** [SalesforceFoundation/Cumulus#1261]
Hi,

On manually running the Recurring donation batch from NPSP Setting tab we are getting 
error: "Attempt to de-reference a null object" in the npsp error logs.

We have simple multi-currency configuration in our org with a single conversion rate.

We are trying to run this manually as the Paid Amount field on Recurring Donation is not getting calculated correctly.

![image](https://cloud.githubusercontent.com/assets/3069322/5699806/8080e5d8-9a56-11e4-8c79-eeae1ae30392.png)

Total No. of Paid installments is 13 and installment amount is 100
so we are expecting Paid Amount to be $1300
Note: Both Donation and Recurring Donation have same currency code (AUD).

Can you please help on this.

Thanks

**Comment by AshwinPandole** [comment]
@kbromer, @njjc - could you please look into this asap as we are getting this in live environment.

**Comment by njjc** [comment]
Hi @AshwinPandole, I'll look into this today. Would you mind enabling login access for Salesforce.com Foundation Support?

**Comment by njjc** [comment]
I'll also need the name and/or org ID of your organization.

**Comment by AshwinPandole** [comment]
I have given access to our sandbox org, we are facing the same issue there as well 
Below Is name and id of Sandbox org 
Cambodian children's fund Australia Inc
00DO0000000WPZc

**Comment by njjc** [comment]
@ceiroa this is the error message I get in the log. I can't find a way to get the stack trace despite being logged in through the LMA. Any ideas?

![image](https://cloud.githubusercontent.com/assets/1018198/5709055/63d11c6a-9a64-11e4-9e83-198d45e6bbce.png)

**Comment by davidhabib** [comment]
is this a scenario where you turn off our error support in custom settings and then redo the scenario, so you see the full error?

**Comment by njjc** [comment]
I forgot we implemented that! Giving it a try now. Thanks!

**Comment by njjc** [comment]
So there is no error on disabling error handling, and that error I got was different than the one @AshwinPandole reported. Ashwin, what steps should I take to reproduce your error?

**Comment by AshwinPandole** [comment]
@njjc 
Create a Recurring donation of monthly installments and mark one of the donations beneath it as Posted. 
The paid amount getting rolled up doesn't show correct value.

Check this record for reference https://cs5.salesforce.com/a08O000000EjSWW
The currency on Recurring donation is AUD and the currency on user (Arxxus Admin) that I'm logged is USD. 
Paid Amount should show value as AUD 100.

**Comment by AshwinPandole** [comment]
@njjc - Where you able to recreate the scenario in the environment ?

**Comment by njjc** [comment]
I haven't been able to reproduce your "Attempt to de-reference a null object" error. I am seeing the incorrect amount in the "Paid Amount" total, which is an error we discussed together and that was fixed previously. I'm attempting to reproduce the error in an apex test in my multicurrency environment now.

**Comment by njjc** [comment]
I've figured out and fixed the issue. Thanks again for your help in reporting the issue, @AshwinPandole. This fix will make it into the package on Tuesday the 20th, at which point you can upgrade manually, and will be pushed to production orgs automatically on Tuesday the 27th.

**Comment by mrbelvedere** [comment]
Included in beta release version 3.31 (Beta 7) and higher

**Comment by mrbelvedere** [comment]
Included in production release version 3.31

**Comment by AshwinPandole** [comment]
We checked our production org and the issue still seems to persist.
Has the fix been published to all orgs ?

**Comment by njjc** [comment]
Not yet, it will be pushed on Tuesday. We have a week period for sandbox testing between release and push upgrade.

**Comment by njjc** [comment]
Oh, that should have been this last Tuesday. @jlantz are we behind on the push?

**Comment by AshwinPandole** [comment]
@jlantz  - Any updates on this. The issue is from live environment and customer is getting anxious.

Thanks for your support.

**Comment by AshwinPandole** [comment]
![image](https://cloud.githubusercontent.com/assets/3069322/6035429/647d3b74-ac59-11e4-8d8e-fad8d1c6f74b.png)

@njjc

**Comment by njjc** [comment]
That version has the fix. Is the issue still with incorrectly converted currency, or is it the "attempt to de-reference a null object" issue originally stated? If you give me login access and repro steps I'll take a look at this too. Sorry for the recurring issues!

**Comment by njjc** [comment]
Also, are these for newly created / updated donations? The existing data won't be fixed until an opportunity related to that recurring donation changes to a closed stage so that the rollups run again.

**Comment by AshwinPandole** [comment]
Yes. We can see its fixed on the newly created records.
Is there a way to fix the existing records without the update to donation ? Since there are quiet a few closed RD as well.
ORG id : 00D90000000fsEY. I have provided access.

**Comment by njjc** [comment]
Unfortunately, there's no way to run the rollups manually. You would have to do it through the data loader.
