### ISSUE TITLE
Investigate (re-architect?) Delete/Undelete Behavior

### ISSUE THREAD

**Issue by ceiroa** [SalesforceFoundation/Cumulus#913]
This comes from ticket https://github.com/SalesforceFoundation/Cumulus/issues/909, but applies to how deletes and undeletes are handled across the entire application. We need to investigate and possibly re-architect how we do cascade deletes.

**Comment by kbromer** [comment]
Also #332

**Comment by mscholtz** [comment]
Hey guys, any word on when this (& #332 ) might be addressed?  It seems to happen not only with 1:1 model, but also with any contact delete that cascade-deletes the Account.  So in the Household model, if my Contact is the only one in their HH Account, and I delete the contact, then I end up with the Account in the recycle bin, but the contact permanently deleted.  This seems like a big problem, given how central the contact is to the NPSP data model..  
@kbromer @ceiroa @davidhabib

**Comment by kbromer** [comment]
Not yet - pull requests readily accepted :)

**Comment by mscholtz** [comment]
@kbromer I don't have the time for this now (and not sure when I would).  But just on the off-chance that I may have the time someday, is there any documentation on how to set up the environment correctly to work on npsp code?  (e,g, not sure which packages are needed, and which should be installed as managed vs pulled in as a repo..)

**Comment by kbromer** [comment]
Indeed - so there's this to start: http://developer.salesforcefoundation.org/Cumulus/Contributor/

@jlantz has also been experimenting with a tool to make the process a bit easier, though I can't recall ATM where that's at...

**Comment by mscholtz** [comment]
thanks

**Comment by judisohn** [comment]
https://mrbelvedere.salesforcefoundation.org/contributor/

**Comment by njjc** [comment]
@mscholtz I've fixed this, should make it into today's release.

**Comment by njjc** [comment]
Actually, I've fixed #332 and not the whole shebang.

**Comment by mscholtz** [comment]
@njjc do you know if your fix will apply to single-contact Household accounts as well?

**Comment by njjc** [comment]
Yep, 1:1 and single contact household accounts both. It would even covers single contacts in a bucket account.

**Comment by mscholtz** [comment]
@njjc awesome!  That's most of what we cared about.  Thanks!

**Comment by judisohn** [comment]
@mscholtz [3.48](https://github.com/SalesforceFoundation/Cumulus/releases/tag/rel%2F3.48) is out in sandboxes - just be aware that for this fix, you do need to delete contacts using the new Delete button override on Contact. I just tested this and it works great - thanks @njjc!!! Just also noted that the Contact still isn't in the recycle bin - but if you restore the Account, the contact now comes along for the restore ride.

**Comment by mscholtz** [comment]
Ah, good to know.  So we're going to need to put that button on our
layouts, right?  And if we delete from a list view or something, we still
see the old behavior?

@njjc just for my own knowledge - I'm curious as to why this happens.  In
what circumstances does a deleted rec not appear in the recycle bin?

On Wed, Aug 12, 2015 at 7:48 AM, Judi Sohn <notifications@github.com> wrote:

> @mscholtz <https://github.com/mscholtz> 3.48
> <https://github.com/SalesforceFoundation/Cumulus/releases/tag/rel%2F3.48>
> is out in sandboxes - just be aware that for this fix, you do need to
> delete contacts using the new Delete button override on Contact. I just
> tested this and it works great - thanks @njjc <https://github.com/njjc>!!!
> Just also noted that the Contact still isn't in the recycle bin - but if
> you restore the Account, the contact now comes along for the restore ride.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SalesforceFoundation/Cumulus/issues/913#issuecomment-130328224>
> .
>



-- 

Matthew Scholtz
Percolator Consulting
(206) 289-0816 x3

http://percolatorconsulting.com/

**Comment by njjc** [comment]
It's a delete button override, so it will work in any contact delete
context. It's not a new button.

The issue is with a contact after delete trigger. We look to see if the
contact's account is system generated (1:1 or household) and if that
contact was the only contact in that account, if those conditions are met,
we delete it to avoid leaving an orphaned account.

Since the contact is a child of account, and the contact is already
deleted, the cascading delete from the account permanently deletes the
contact in the recycle bin.
